//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/ProjectFiles/Scripts/Player/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""PlayerInputMap"",
            ""id"": ""b251fdee-838c-402f-8553-d6e3c5e9ad61"",
            ""actions"": [
                {
                    ""name"": ""ForwardBackward"",
                    ""type"": ""Value"",
                    ""id"": ""8e438592-f7c9-43cb-8798-b662c07f0103"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightLeft"",
                    ""type"": ""Value"",
                    ""id"": ""e64e3101-ed81-44f6-925b-fa3133fd0cc9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Diagonal_East"",
                    ""type"": ""Button"",
                    ""id"": ""8b0cceb4-9d44-4828-998b-202793d20488"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Diagonal_West"",
                    ""type"": ""Button"",
                    ""id"": ""8a4aec90-3265-4551-a73d-68e6aac1de46"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""eea2d199-9e60-444b-9f74-a1d0d4874c40"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ForwardBackward"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c01c7189-dd0f-437f-9328-bc156ddeac2f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ForwardBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""8ec7f734-ba05-4c79-93f3-02b843aa3622"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ForwardBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b48eb059-27f2-4b7b-b6c4-efec01a4f4c3"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Diagonal_East"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""bbf89334-8424-4adc-ab1e-a4f607b72f14"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightLeft"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""43b8a27f-014a-421a-9751-add155ca9624"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""abe846c3-7947-4686-8571-e9e91cb3b4e1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a8c82a67-bd74-45d5-bb37-ed5a583c533e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Diagonal_West"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInputMap
        m_PlayerInputMap = asset.FindActionMap("PlayerInputMap", throwIfNotFound: true);
        m_PlayerInputMap_ForwardBackward = m_PlayerInputMap.FindAction("ForwardBackward", throwIfNotFound: true);
        m_PlayerInputMap_RightLeft = m_PlayerInputMap.FindAction("RightLeft", throwIfNotFound: true);
        m_PlayerInputMap_Diagonal_East = m_PlayerInputMap.FindAction("Diagonal_East", throwIfNotFound: true);
        m_PlayerInputMap_Diagonal_West = m_PlayerInputMap.FindAction("Diagonal_West", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInputMap
    private readonly InputActionMap m_PlayerInputMap;
    private List<IPlayerInputMapActions> m_PlayerInputMapActionsCallbackInterfaces = new List<IPlayerInputMapActions>();
    private readonly InputAction m_PlayerInputMap_ForwardBackward;
    private readonly InputAction m_PlayerInputMap_RightLeft;
    private readonly InputAction m_PlayerInputMap_Diagonal_East;
    private readonly InputAction m_PlayerInputMap_Diagonal_West;
    public struct PlayerInputMapActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerInputMapActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ForwardBackward => m_Wrapper.m_PlayerInputMap_ForwardBackward;
        public InputAction @RightLeft => m_Wrapper.m_PlayerInputMap_RightLeft;
        public InputAction @Diagonal_East => m_Wrapper.m_PlayerInputMap_Diagonal_East;
        public InputAction @Diagonal_West => m_Wrapper.m_PlayerInputMap_Diagonal_West;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInputMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputMapActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputMapActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputMapActionsCallbackInterfaces.Add(instance);
            @ForwardBackward.started += instance.OnForwardBackward;
            @ForwardBackward.performed += instance.OnForwardBackward;
            @ForwardBackward.canceled += instance.OnForwardBackward;
            @RightLeft.started += instance.OnRightLeft;
            @RightLeft.performed += instance.OnRightLeft;
            @RightLeft.canceled += instance.OnRightLeft;
            @Diagonal_East.started += instance.OnDiagonal_East;
            @Diagonal_East.performed += instance.OnDiagonal_East;
            @Diagonal_East.canceled += instance.OnDiagonal_East;
            @Diagonal_West.started += instance.OnDiagonal_West;
            @Diagonal_West.performed += instance.OnDiagonal_West;
            @Diagonal_West.canceled += instance.OnDiagonal_West;
        }

        private void UnregisterCallbacks(IPlayerInputMapActions instance)
        {
            @ForwardBackward.started -= instance.OnForwardBackward;
            @ForwardBackward.performed -= instance.OnForwardBackward;
            @ForwardBackward.canceled -= instance.OnForwardBackward;
            @RightLeft.started -= instance.OnRightLeft;
            @RightLeft.performed -= instance.OnRightLeft;
            @RightLeft.canceled -= instance.OnRightLeft;
            @Diagonal_East.started -= instance.OnDiagonal_East;
            @Diagonal_East.performed -= instance.OnDiagonal_East;
            @Diagonal_East.canceled -= instance.OnDiagonal_East;
            @Diagonal_West.started -= instance.OnDiagonal_West;
            @Diagonal_West.performed -= instance.OnDiagonal_West;
            @Diagonal_West.canceled -= instance.OnDiagonal_West;
        }

        public void RemoveCallbacks(IPlayerInputMapActions instance)
        {
            if (m_Wrapper.m_PlayerInputMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputMapActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputMapActions @PlayerInputMap => new PlayerInputMapActions(this);
    public interface IPlayerInputMapActions
    {
        void OnForwardBackward(InputAction.CallbackContext context);
        void OnRightLeft(InputAction.CallbackContext context);
        void OnDiagonal_East(InputAction.CallbackContext context);
        void OnDiagonal_West(InputAction.CallbackContext context);
    }
}
